driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

transport:
  name: dokken

provisioner:
  name: dokken
  chef_log_level: info
  chef_output_format: minimal

verifier:
  name: inspec
  sudo: false

platforms:
- name: amazonlinux
  driver:
    image: dokken/amazonlinux
    pid_one_command: /sbin/init

- name: amazonlinux-2
  driver:
    image: dokken/amazonlinux-2
    pid_one_command: /usr/lib/systemd/systemd

- name: debian-8
  driver:
    image: dokken/debian-8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: debian-9
  driver:
    image: dokken/debian-9
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: centos-6
  driver:
    image: dokken/centos-6
    pid_one_command: /sbin/init

- name: centos-7
  driver:
    image: dokken/centos-7
    pid_one_command: /usr/lib/systemd/systemd

- name: oracle-6.6
  driver:
    image: oraclelinux:6.6
- name: oracle-6.7
  driver:
    image: oraclelinux:6.7
- name: oracle-7.1
  driver:
    image: oraclelinux:7.1
    pid_one_command: /usr/lib/systemd/systemd

- name: ubuntu-14.04
  driver:
    image: dokken/ubuntu-14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: ubuntu-18.04
  driver:
    image: dokken/ubuntu-18.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

suites:
  - name: default # run inspec locally
    run_list:
      - recipe[test_helper::setup]
      - recipe[audit::default]
    attributes:
      audit:
        reporter: json-file
        profiles:
          - name: ssh-hardening
            url: https://github.com/dev-sec/tests-ssh-hardening/archive/master.zip
          - name: ssh-baseline
            supermarket: dev-sec/ssh-baseline
  - name: inspec-attributes
    run_list:
      - recipe[test_helper::setup]
      - recipe[test_helper::create_file]
      - recipe[audit::default]
    attributes:
      audit:
        reporter: json-file
        profiles:
          - git: https://github.com/mhedgpeth/attribute-file-exists-profile.git
        attributes:
          file: /opt/kitchen/cache/attribute-file-exists.test
  - name: chef-node-enabled
    run_list:
      - recipe[audit::default]
    attributes:
      audit:
        reporter: json-file
        profiles:
          - url: https://github.com/adamleff/inspec-profile-chef-node-attributes/archive/master.tar.gz
        chef_node_attribute_enabled: true
  - name: chef-node-disabled
    run_list:
      - recipe[audit::default]
    attributes:
      audit:
        reporter: json-file
        profiles:
          - url: https://github.com/adamleff/inspec-profile-chef-node-attributes/archive/master.tar.gz
  - name: missing-profile-no-fail
    run_list:
      - recipe[test_helper::setup]
      - recipe[audit::default]
    attributes:
      audit:
        reporter: json-file
        profiles:
          - name: ssh-hardening
            url: https://github.com/dev-sec/this-is-not-available.zip
    includes:
      - ubuntu-14.04
  - name: missing-profile-fail
    run_list:
      - recipe[test_helper::setup]
      - recipe[audit::default]
    attributes:
      audit:
        reporter: json-file
        fail_if_not_present: true
        profiles:
          - name: ssh-hardening
            url: https://github.com/dev-sec/this-is-not-available.zip
    includes:
      - ubuntu-14.04
  - name: compliance # compliance direct reporting
    run_list:
      - recipe[audit::default]
    attributes:
      audit:
        server: <%= ENV['COMPLIANCE_API'] %>
        token: <%= ENV['COMPLIANCE_ACCESSTOKEN'] %>
        owner: admin
        profiles:
          - name: ssh-hardening
            url: https://github.com/dev-sec/tests-ssh-hardening/archive/master.zip
          - git: https://github.com/dev-sec/tests-ssh-hardening.git
          - name: ssh-baseline
            supermarket: dev-sec/ssh-baseline
  - name: gem-install-version
    run_list:
      - recipe[test_helper::install_inspec]
      - recipe[audit::default]
    attributes:
      audit:
        reporter: json-file
        inspec_version: 1.29.0
        fail_if_not_present: true
  - name: gem-install-core-version
    run_list:
      - recipe[test_helper::install_inspec]
      - recipe[audit::default]
    attributes:
      audit:
        reporter: json-file
        inspec_version: 2.1.67
        fail_if_not_present: true
  - name: skip-inspec-gem-install
    run_list:
      - recipe[test_helper::install_inspec]
      - recipe[audit::default]
    attributes:
      audit:
        reporter: json-file
        inspec_version: 1.25.1
        fail_if_not_present: true
  - name: chef-12-test
    run_list:
      - recipe[audit::default]
    attributes:
      audit:
        reporter: json-file
        inspec_version: 1.25.1
        fail_if_not_present: true
  - name: hash
    run_list:
      - recipe[audit::default]
    attributes:
      audit:
        reporter: json-file
        profiles:
          ssh-hardening:
            url: https://github.com/dev-sec/tests-ssh-hardening/archive/master.zip
          ssh-baseline:
            supermarket: dev-sec/ssh-baseline
