dist: xenial

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=default-centos-7 CHEF_VERSION=13.0.118
  - INSTANCE=default-ubuntu-1404 CHEF_VERSION=13.0.118
  - INSTANCE=missing-profile-no-fail-ubuntu-1404 CHEF_VERSION=13.0.118
  - INSTANCE=missing-profile-fail-ubuntu-1404 CHEF_VERSION=13.0.118
  - INSTANCE=gem-install-version-centos-7 CHEF_VERSION=13.0.118
  - INSTANCE=gem-install-version-ubuntu-1404 CHEF_VERSION=13.0.118
  - INSTANCE=gem-install-core-version-ubuntu-1404 CHEF_VERSION=13.0.118
  - INSTANCE=default-centos-7 CHEF_VERSION=13.0.118 CHEF_VERSION=13.0.118
  - INSTANCE=skip-inspec-gem-install-ubuntu-1404 CHEF_VERSION=13.0.118
  - INSTANCE=inspec-attributes-ubuntu-1404 CHEF_VERSION=13.0.118
  - INSTANCE=chef-node-enabled-ubuntu-1404 CHEF_VERSION=13.0.118
  - INSTANCE=chef-node-disabled-ubuntu-1404 CHEF_VERSION=13.0.118
  - INSTANCE=hash-centos-7 CHEF_VERSION=13.0.118
  - INSTANCE=hash-ubuntu-1404 CHEF_VERSION=13.0.118

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
